default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer # Trims end of files.
        exclude: web_ui/.pnp.cjs
      - id: check-yaml # Checks for valid yaml
        exclude: template.yaml
      - id: debug-statements # Checks for breakpoint() + debuggers
        exclude: "server/cli/.*|server/scripts/.*"
      - id: check-merge-conflict # Checks for merge conflict strings
      - id: check-toml # Checks toml parsibility.
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.11
        files: "^(server|lambdas|.buildkite)/"
  - repo: local
    hooks:
      - id: isort
        name: sort imports
        entry: bash -c 'isort --profile black .'
        language: system
  - repo: local
    hooks:
      - id: mypy
        name: type check
        verbose: true
        entry: bash -c 'mypy .'
        language: system
        pass_filenames: false
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
    - id: pydocstyle
      args:
      - --match-dir='^(pytest_bq)'
